### ISSUE TITLE
Регистр первой буквы названия файлов 

### ISSUE THREAD

**Issue by SoprachevAK** [StranikS-Scan/WorldOfTanks-Decompiled#10]
Многие файлы декомпилировались с маленькой буквы, например [scripts/client/avatar.py](https://github.com/StranikS-Scan/WorldOfTanks-Decompiled/blob/1.14/source/res/scripts/client/avatar.py), хотя во второй строке файла чётко указано, что он должен быть с большой `# Embedded file name: scripts/client/Avatar.py`

Другие файлы исходника импортируют этот файл с большой, [например вот](https://github.com/StranikS-Scan/WorldOfTanks-Decompiled/blob/19e5f81e2ec818181f83264c9d9dbfbc92cc9baa/source/res/scripts/client/visual_script_client/scene_blocks.py#L16)

Это баг или осмысленное решение? PyCharm например ругается на попытку импорта из файла с ошибкой в регистре

**Comment by StranikS-Scan** [comment]
![image](https://user-images.githubusercontent.com/9452878/130560549-2cfc7c16-0346-444b-aed0-706956899466.png)

Читай описание к репо, в конце там все написано.
