### ISSUE TITLE
New update 1.14.1.2 #1060

### ISSUE THREAD

**Issue by Kostya12rus** [StranikS-Scan/WorldOfTanks-Decompiled#11]
Пожалуйста обновите до последней версии, она вышла 29.10

**Comment by StranikS-Scan** [comment]
Зачем?

**Comment by Kostya12rus** [comment]
Я думаю там что то поменялось, они же выпустили баг фикс

**Comment by StranikS-Scan** [comment]
Это микропатчи для вкл/выкл ивентов. Ничего там нет в них.
