### ISSUE TITLE
Downloading PjOrion

### ISSUE THREAD

**Issue by nihadenes** [StranikS-Scan/WorldOfTanks-Decompiled#12]
Is there a version of PjOrion I can download? All downloads in websites are expired and links are not working.

**Comment by StranikS-Scan** [comment]
[https://koreanrandom.com/forum/topic/15280-](https://koreanrandom.com/forum/topic/15280-)

**Comment by nihadenes** [comment]
Thank you, I didn't know I need to sign up to download this file 🤣
