### ISSUE TITLE
File duplicates

### ISSUE THREAD

**Issue by Monstrofil** [StranikS-Scan/WorldOfTanks-Decompiled#6]
Hi, seems this files are completely duplicated, probably one should be deleted:
https://github.com/StranikS-Scan/WorldOfTanks-Decompiled/blob/1.10/source/res/scripts/entity_defs/Account.def
https://github.com/StranikS-Scan/WorldOfTanks-Decompiled/blob/1.10/source/res/scripts/entity_defs/account.def

**Comment by StranikS-Scan** [comment]
https://github.com/StranikS-Scan/WorldOfTanks-Decompiled#files-with-different-case-of-letters

**Comment by Monstrofil** [comment]
Oh, that hepls! But anyway I don't understand, why do you keep duplicates in repository?

**Comment by Monstrofil** [comment]
`WG created this problem when it started renaming its files. Duplicates are created by github automatically on the server. To fix the problems I need to create a new repo. However, when WG renames another part of the files again, the problem will appear again .... Use the archive from the zip\ folder, it always contains files with the correct names.`

GitHub cannot "create duplicates" itself, that is definitely issue with git. Probably you unpack files to same folder, then commit them and push to github? I guess that is the wrong way and you should just do `rm -rf` in sources folder before updating files, then git will just mark files as "renamed".

Or just use Linux :)

**Comment by Monstrofil** [comment]
Ok, what I tried:
- run git config core.ignorecase false
- remove everything from sources folder
- do git add && git commit
- run Zip-Unpacker.exe
- run git add && git commit --amend

As a resut I got commit that removes all duplicates from repository.

**Comment by StranikS-Scan** [comment]
> Probably you unpack files to same folder, then commit them and push to github?

No of course.

This problem cannot be completely solved as long as WG allows its programmers to change the case of letters in the names of scripts.

**Comment by Monstrofil** [comment]
@StranikS-Scan what about recipe that I posted on 23 sep? Did you try it? Why do you think it is not suitable?

Here is an example with removal of duplicates from repository by guide from https://github.com/StranikS-Scan/WorldOfTanks-Decompiled/issues/6#issuecomment-697425369
https://github.com/Monstrofil/WorldOfTanks-Decompiled/commit/c49eaee287fe5a95519f5553546a68563e8dc7f7

**Comment by StranikS-Scan** [comment]
This will break the chain of changes between commits in the tree. This is the same as creating a new repo. This solution does not suit me.

**Comment by Monstrofil** [comment]
Chain of file changes is broken even now. 

Anyway, you are the owner, so do whatever you think is better. I'm closing this issue.
