### ISSUE TITLE
You are amazing!

### ISSUE THREAD

**Issue by y4n6** [StranikS-Scan/WorldOfTanks-Decompiled#7]
Where did you learn WOT mods development?
How do you know API of BigWorld?
How do you know API of  WoT Client Hooks?
If I want to understand mod_AdvancedAimingSystem.py, How should I learn?
It would be my pleasure if I could get your email.

**Comment by StranikS-Scan** [comment]
I recommend creating a theme on the site https://koreanrandom.com/forum/
